name: Master Push
on:
  push:
    branches:
      - 'main'
jobs:
  prerelease:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    name: Create release
    steps:
      - uses: actions/checkout@v3
      - name: Semantic release
        id: semantic
        uses: codfish/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Merge main -> development
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: develop
          message: "chore: Merge master branch [skip ci]"
          github_token: ${{ secrets.GITHUB_TOKEN }}
